"""initial schema

Revision ID: 7d43822ad7ad
Revises: 
Create Date: 2026-06-04 20:45:36.321178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d43822ad7ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('chief_complaint', sa.String(length=255), nullable=False),
    sa.Column('pain_score', sa.Integer(), nullable=False),
    sa.Column('medication_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('triage_assessments',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('clinician_id', sa.String(length=36), nullable=False),
    sa.Column('ai_priority', sa.Integer(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('shap_explanation', sa.JSON(), nullable=True),
    sa.Column('clinician_priority', sa.Integer(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.String(length=10), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('vitals',
    sa.Column('vital_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=False),
    sa.Column('sbp', sa.Integer(), nullable=False),
    sa.Column('dbp', sa.Integer(), nullable=False),
    sa.Column('respiratory_rate', sa.Integer(), nullable=False),
    sa.Column('spo2', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('gcs', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('vital_id')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=True),
    sa.Column('clinician_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['triage_assessments.assessment_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))

    op.drop_table('audit_log')
    op.drop_table('vitals')
    op.drop_table('triage_assessments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
